services:
  # PostgreSQL database
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: fantasy_draft
      POSTGRES_USER: fantasy_user
      POSTGRES_PASSWORD: fantasy_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./fantasy-projections-api/database/schema:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fantasy_user -d fantasy_draft"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fantasy-network

  # Redis cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - fantasy-network

  # Fantasy Projections API Backend
  api:
    build:
      context: ./fantasy-projections-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://fantasy_user:fantasy_pass@postgres:5432/fantasy_draft
      REDIS_URL: redis://redis:6379/0
      ENVIRONMENT: development
      PYTHONPATH: /app/src
      JWT_SECRET_KEY: "dev-secret-key-that-should-be-changed-in-production-1234567890abcdefghijklmnopqrstuvwxyz"
      CORS_ORIGINS: "http://localhost:3000,http://frontend:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./fantasy-projections-api/data:/app/data:ro
      - ./fantasy-projections-api/src:/app/src
      - ./fantasy-projections-api/output:/app/output
    command: uvicorn fantasy_projections.api.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import requests; requests.get('http://localhost:8000/api/health')\" || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fantasy-network

  # Celery worker for background tasks
  celery-worker:
    build:
      context: ./fantasy-projections-api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://fantasy_user:fantasy_pass@postgres:5432/fantasy_draft
      REDIS_URL: redis://redis:6379/0
      ENVIRONMENT: development
      PYTHONPATH: /app/src
      JWT_SECRET_KEY: "dev-secret-key-that-should-be-changed-in-production-1234567890abcdefghijklmnopqrstuvwxyz"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./fantasy-projections-api/data:/app/data:ro
      - ./fantasy-projections-api/src:/app/src
      - ./fantasy-projections-api/output:/app/output
      - /tmp/uploads:/tmp/uploads
    command: python scripts/start_celery_worker.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c 'from fantasy_projections.api.background.celery_app import celery_app; exit(0 if celery_app.control.ping() else 1)'"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 30s
    networks:
      - fantasy-network

  # Fantasy Projections Web Frontend
  frontend:
    build:
      context: ./fantasy-projections-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:8000
      NEXT_TELEMETRY_DISABLED: 1
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - fantasy-network

volumes:
  postgres_data:
  redis_data:

networks:
  fantasy-network:
    driver: bridge