# Development overrides for docker-compose.yml
# This file is automatically loaded by docker compose in development

services:
  # Development-specific overrides for the API
  api:
    environment:
      LOG_LEVEL: debug
    volumes:
      # Mount source code for hot reloading
      - ./fantasy-projections-api/src:/app/src
      - ./fantasy-projections-api/data:/app/data:ro
      - ./fantasy-projections-api/output:/app/output
    # Use development command with reload
    command: uvicorn fantasy_projections.api.main:app --host 0.0.0.0 --port 8000 --reload

  # Development-specific overrides for the frontend
  web:
    environment:
      NODE_ENV: development
      # Enable Next.js development features
      WATCHPACK_POLLING: true
    volumes:
      # Mount source for hot reloading (but exclude node_modules and .next)
      - ./fantasy-projections-web/src:/app/src
      - ./fantasy-projections-web/public:/app/public
      - ./fantasy-projections-web/package.json:/app/package.json
      - ./fantasy-projections-web/package-lock.json:/app/package-lock.json
      - ./fantasy-projections-web/next.config.mjs:/app/next.config.mjs
      - ./fantasy-projections-web/tailwind.config.ts:/app/tailwind.config.ts
      - ./fantasy-projections-web/tsconfig.json:/app/tsconfig.json
      - ./fantasy-projections-web/postcss.config.mjs:/app/postcss.config.mjs
      # Named volume for node_modules to avoid conflicts
      - web_node_modules:/app/node_modules
    # Development server with hot reload
    command: ["sh", "-c", "npm ci && npm run dev"]

volumes:
  # Named volume for frontend node_modules in development
  web_node_modules: